package com.toast.tcblog.todo.dao;

import com.toast.tcblog.todo.dto.Todos;
import com.toast.tcblog.todo.dto.TodosExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TodosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbggenerated Fri Jun 19 17:07:27 KST 2015
     */
    int countByExample(TodosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbggenerated Fri Jun 19 17:07:27 KST 2015
     */
    int deleteByExample(TodosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbggenerated Fri Jun 19 17:07:27 KST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbggenerated Fri Jun 19 17:07:27 KST 2015
     */
    int insert(Todos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbggenerated Fri Jun 19 17:07:27 KST 2015
     */
    int insertSelective(Todos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbggenerated Fri Jun 19 17:07:27 KST 2015
     */
    List<Todos> selectByExample(TodosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbggenerated Fri Jun 19 17:07:27 KST 2015
     */
    Todos selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbggenerated Fri Jun 19 17:07:27 KST 2015
     */
    int updateByExampleSelective(@Param("record") Todos record, @Param("example") TodosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbggenerated Fri Jun 19 17:07:27 KST 2015
     */
    int updateByExample(@Param("record") Todos record, @Param("example") TodosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbggenerated Fri Jun 19 17:07:27 KST 2015
     */
    int updateByPrimaryKeySelective(Todos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbggenerated Fri Jun 19 17:07:27 KST 2015
     */
    int updateByPrimaryKey(Todos record);
}