package com.toast.tcblog.todo.dto;

public class Todos {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todos.id
     *
     * @mbggenerated Fri Jun 19 17:07:27 KST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todos.name
     *
     * @mbggenerated Fri Jun 19 17:07:27 KST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todos.completed
     *
     * @mbggenerated Fri Jun 19 17:07:27 KST 2015
     */
    private String completed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todos.id
     *
     * @return the value of todos.id
     *
     * @mbggenerated Fri Jun 19 17:07:27 KST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todos.id
     *
     * @param id the value for todos.id
     *
     * @mbggenerated Fri Jun 19 17:07:27 KST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todos.name
     *
     * @return the value of todos.name
     *
     * @mbggenerated Fri Jun 19 17:07:27 KST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todos.name
     *
     * @param name the value for todos.name
     *
     * @mbggenerated Fri Jun 19 17:07:27 KST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todos.completed
     *
     * @return the value of todos.completed
     *
     * @mbggenerated Fri Jun 19 17:07:27 KST 2015
     */
    public String getCompleted() {
        return completed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todos.completed
     *
     * @param completed the value for todos.completed
     *
     * @mbggenerated Fri Jun 19 17:07:27 KST 2015
     */
    public void setCompleted(String completed) {
        this.completed = completed;
    }
}